### ISSUE TITLE
 Rework HDFS TLS / Auth structs

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/hdfs-operator#289]
See https://github.com/stackabletech/issues/issues/293 for details

**Comment by maltesander** [comment]
This is not about TLS / Auth structs since they do not exist yet, but the top-level properties
- `auto_format_fs`
- `dfs_replication`
- `vector_aggregator_config_map_name`
- `zookeeper_config_map_name`

could be moved to the new global `clusterConfig`.

This will be breaking and must be adapted in all HDFS dependent operator examples and tests:

## TODO

- [x] https://github.com/stackabletech/hdfs-operator/pull/326
- [x] https://github.com/stackabletech/druid-operator/pull/411
- [x] https://github.com/stackabletech/hbase-operator/pull/326
- [x] https://github.com/stackabletech/trino-operator/pull/394
- [x] ~~Adapt stackablectl demos~~ -> Will be done before next release

I hope this is all.

**Comment by maltesander** [comment]
All done
