### ISSUE TITLE
Implement Authorizer

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/hdfs-operator#400]
In order to allow authorizing HDFS access requests with OPA, we need to implement a component to run inside of HDFS and forward requests to OPA, this is a principle very similar to the ones we currently use in [Kafka](https://github.com/StyraInc/opa-kafka-plugin), [Druid](https://github.com/stackabletech/druid-opa-authorizer) and which is being merged in upstream [Trino](https://github.com/trinodb/trino/pull/19532) as well. 

There is some code at https://github.com/stackabletech/hdfs-opa-authorizer where I have played around a bit, but none of this should be taken as gospel, if it seems weird then that is because it is weird and wasn't thought through!

The authorizer should implement HDFS' internal authorizer interface, serialize the relevant information from the context and forward it to a configurable OPA server.

Configuration could either be done via the HDFS config mechanism or in a first stage via environment variables.

```[tasklist]
### Tasks
- [x] Initial release of HDFS authorizer
- [x] Add HDFS authorizer to Stackable HDFS docker image
- [x] Update [authorization section](https://docs.stackable.tech/home/stable/hdfs/usage-guide/security#_authorization) in the docs. Document the JSON object that comes in when writing rules. ideally also give some example rules.
- [ ] https://github.com/stackabletech/docker-images/pull/555
- [x] feature tracker updated
```

**Comment by lfrancke** [comment]
I just looked at the Group Mapper and just wanted to give a heads-up that I'd like Java projects to follow the example of the Druid Authorizer in terms of code style and setup etc.

(I haven't looked at your code yet)

I can help if needed.

**Comment by sbernauer** [comment]
Alright :+1:

**Comment by lfrancke** [comment]
Please link to documentation here

**Comment by sbernauer** [comment]
*nightly* doc link: https://docs.stackable.tech/home/nightly/hdfs/usage-guide/security#_authorization
