### ISSUE TITLE
Document where to find production ready rego rules

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/hdfs-operator#516]
```[tasklist]
### Tasks
- [x] Link to hdfs-utils repo
- [x] Link to integration tests folder
- [x] Provide a short example and explanation of the example
```
